{{- if .Values.useWebhook -}}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "oam-kubernetes-runtime.fullname" . }}
  labels:
    {{- include "oam-kubernetes-runtime.selectorLabels" . | nindent 4 }}
webhooks:
  - name: "validate.applicationconfigurations.core.oam.dev"
    rules:
      - apiGroups:   ["core.oam.dev"]
        apiVersions: ["v1alpha2"]
        operations:  ["CREATE", "UPDATE","DELETE"]
        resources:   ["applicationconfigurations"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: {{.Release.Namespace}}
        name: {{ template "oam-kubernetes-runtime.name" . }}-webhook
        path: /validating-applicationconfigurations
      caBundle: "{{.Values.certificate.caBundle}}"
    admissionReviewVersions: ["v1beta1"]
    failurePolicy: Fail
    timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "oam-kubernetes-runtime.name" . }}-webhook
  labels:
    {{- include "oam-kubernetes-runtime.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  ports:
    - port: 443
      targetPort: {{ .Values.webhookService.port }}
      protocol: TCP
      name: https
  selector:
    {{ include "oam-kubernetes-runtime.selectorLabels" . | nindent 6 }}

{{- end -}}